PUP-BSIT/project-club-404

codes/login2.css, codes/login2.html, codes/login2.js
Please review the draft page if there are any issues. Thank you
=> Upload login and register draft page.

heybleepi/codes/form.html, heybleepi/codes/form_script.js
Please check if there are any issues with the adjustments. Thank you
=> add icons on each input field

heybleepi/codes/form.html, heybleepi/codes/form_script.js, heybleepi/codes/form_style.css
Please review my changes to our login and registration form.
=> Refactor login and register form

heybleepi/codes/form.html
=> Update register interface

heybleepi/codes/configuration.php, heybleepi/codes/form_script.js, heybleepi/codes/index.php, heybleepi/codes/users.php
Please check the code to see if there are any issues. Thank you.
=> Add php files and another functions in JS file.

heybleepi/codes/index.php, heybleepi/codes/users.php
Please check the code to see if there any issue. Thanks!
=> Update changes in php files.

heybleepi/codes/messages.css, heybleepi/codes/messages.js, heybleepi/codes/messages.php
Could you please review my code for the initial messaging feature?
Let me know if you have any suggestions or notice any issues, especially regarding the database connection setup and overall structure.
Thank you!
=> Add inital message feature files.

heybleepi/codes/dashboard.css, heybleepi/codes/dashboard.html, heybleepi/codes/dashboard.js
=> Add initial dashboard

heybleepi/codes/dashboard.css, heybleepi/codes/dashboard.js
Please check if the styles for reaction buttons is already good.
=> Enhance style reaction button

heybleepi/codes/dashboard.css, heybleepi/codes/dashboard.html, heybleepi/codes/dashboard.js
Please review the code for disabling the post button
=> Disable button for create post

heybleepi/codes/dashboard.css, heybleepi/codes/dashboard.html, heybleepi/codes/dashboard.js
Please review the new dashboard style
=> Enhance dashboard style

heybleepi/codes/dashboard.html, heybleepi/codes/dashboard.js
=> Enhance UI for improve user experience

heybleepi/codes/script/settings.js, heybleepi/codes/settings.html, heybleepi/codes/stylesheet/settings.css
Please review the CSS file if there are any issues. thank you
=> Update background image and color of interface.

heybleepi/codes/settings.html, heybleepi/codes/stylesheet/settings.css
Good evening, please review the changes I made to your settings & privacy. I fix the buttons and I add the logo from the other group for our social media connection. Thank you!
=> Enhance UI to settings & privacy

heybleepi/codes/messages.html, heybleepi/codes/stylesheet/messages.css
Please review the changes to message page, I made changes to it's design and added a message preview.
=> Enhance message page UI

heybleepi/codes/script/settings.js, heybleepi/codes/settings.html, heybleepi/codes/stylesheet/settings.css
Please review the updated interface of the settings if there are any issues. Thank you
=> Update settings interface and responsiveness.

heybleepi/codes/profile.html, heybleepi/codes/profile_edit.html, heybleepi/codes/stylesheet/profile_edit.css
Please review the changes to edit profile and if the design is already match
=> add change edit profile

heybleepi/codes/profile.html, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
Please review the new feature I added. Thank you!
=> feat: add dynamic comment functionality for new posts

heybleepi/codes/script/form_script.js
Please review my code for check ing the username status at form_script.js
=> feat(login and  register): add check status for username

heybleepi/codes/php/logout.php, heybleepi/codes/php/settings.php, heybleepi/codes/php/update_settings.php, heybleepi/codes/stylesheet/settings.css
Please review the update settings I added to your settings & privacy
=> feat(settings&privacy): add update settings

heybleepi/codes/php/dashboard.php
Please review the changes in dashboard .php
=> feat(dashboard): add logout button

heybleepi/codes/php/profile.php
Pleases review my code. thank you!
=> feat(profile): add real username base on the user input

heybleepi/codes/php/messages.php
Please review and let me know if further adjustments are needed.
=> refactor(messages): remove the input field from messages.

heybleepi/codes/php/check_username.php, heybleepi/codes/php/profile_edit.php
Please review the changes I made in edit profile and for the username checker.
=> add change in edit profile

heybleepi/codes/php/configuration.php
Please review the configuration for our database at Hostinger
=> fix(configuration): fix db connection

heybleepi/codes/php/users.php
Please review the  changes on our endpoint
=> feat(endpoint): add username validation

heybleepi/codes/php/users.php
Please review the changes in users.php
=> refactor(users:): remove session start

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/index.php, heybleepi/codes/php/profile.php, heybleepi/codes/php/profile_edit.php, heybleepi/codes/php/settings.php, heybleepi/codes/php/users.php
Please review the changes if there are any issues. Thank you
=> changes(php):  add changes to headers of php files and queries.

heybleepi/codes/php/delete_account.php, heybleepi/codes/php/settings.php, heybleepi/codes/script/settings.js
Please review the initial function of account deletion if there are any issues. Thank you!
=> test(settings): add function to delete account.

heybleepi/codes/php/messages.php
Please review my code and let me know if there are any issues.
=> fix(messages): change session key from user_name to username

heybleepi/codes/stylesheet/messages.css
Please review the changes in messages.css and let me know if the styles look good or need any adjustments.
=> style(messages): update and improve styles in messages.css

heybleepi/codes/php/delete_account.php, heybleepi/codes/php/settings.php, heybleepi/codes/php/update_password.php, heybleepi/codes/php/update_settings.php, heybleepi/codes/php/users.php, heybleepi/codes/script/settings.js
Please review the test functions for the settings if there are any issues. Thank you!
=> test(settings) add initial functions for deletion of account, updating account information and password.

heybleepi/codes/stylesheet/messages.css
Please let me know if the style changes look good or if further adjustments are needed. Thank you!
=> styles(messages): add changes in styles for messages

heybleepi/codes/php/dashboard.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
Please review the changes for our global posting
=> feat(dashboard): add text post, comment, and likes.

heybleepi/codes/php/dashboard.php
Please review the change to logout
=> feat(dashboard): add logout to the sidebar

heybleepi/codes/php/comment_actions.php, heybleepi/codes/php/dashboard.php, heybleepi/codes/php/delete_comment.php, heybleepi/codes/php/edit_comment.php, heybleepi/codes/script/dashboard.js
Please review the changes I made in the comment section. I add a edit and delete for the authors
=> feat(dashboard): add edit and delete comment.

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/like_toggle.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
Please review the like feature I added
=> feat(dashboard): add likes to the post

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/profile.php, heybleepi/codes/php/share_post.php, heybleepi/codes/php/share_toggle.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
Please review our new feature (share post)
=> feat(profile and dashboard): add share post

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/profile.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
Please review the new feature (image uploading)
=> feat(profile and dashboard): add image upload

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/profile.php
Please review the changes. Thank you!
=> feat(profile and dashboard): show image to shared content

heybleepi/codes/php/profile.php
Please review the changes in profile.php notification
=> feat(profile): reflect the notification to profile

heybleepi/codes/php/dashboard.php, heybleepi/codes/stylesheet/dashboard.css
=> feat(dashboard): add message unread badge count

heybleepi/codes/php/profile.php, heybleepi/codes/php/profile_edit.php, heybleepi/codes/script/profile_edit.js, heybleepi/codes/stylesheet/dashboard.css, heybleepi/codes/stylesheet/profile_edit.css
=> feat(edit profile): integrate user profile update and preview across profile_edit and profile view

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/profile_edit.php, heybleepi/codes/php/users.php
Please review the changes in dashboard
=> fix(dashboard): reflect latest profile picture and name after edits

heybleepi/codes/php/dashboard.php
Please review my code for post options
=> fix(dashboard): post-option for creator and non-creator

heybleepi/codes/php/profile.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
Please review the changes in profile
=> feat(profile): add lightbox modal for viewing photos and videos in profile gallery

README.md
=> style: add tagline

heybleepi/codes/php/messages.php
Please check my code if there any issues.
=> fix(messages): update emoji picker implementation

heybleepi/codes/stylesheet/messages.css
Please check my code if there any issues.
=> styles(messages): update changes styles for messages

heybleepi/codes/php/delete_account.php, heybleepi/codes/php/settings.php, heybleepi/codes/php/update_password.php, heybleepi/codes/php/update_settings.php, heybleepi/codes/script/settings.js, heybleepi/codes/stylesheet/settings.css
Please review the changes in codes for settings. Thank you
=> test(settings) add initial functions for update info, update password and delete account.

heybleepi/codes/php/check_album.php, heybleepi/codes/php/create_album.php, heybleepi/codes/php/dashboard.php, heybleepi/codes/php/profile.php, heybleepi/codes/php/view_album.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
I add a feature where user can create a multiple image and video to their album, please review. In addition to that, I fix the size of image/video to our feed.
=> feat(profile and dashboard): add multiple image and video with preview

heybleepi/codes/php/messages.php
Please check my code if there any issues. Thank you.
=> refactor(messages): refactor message logic to use user_id for foreign key compliance

heybleepi/codes/php/messages.php
Please check my code if there any issues.
=> refactor(messages): update messages handling to comply with foreign key constraints

heybleepi/codes/php/profile.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
The multiple media uploads is now working with standard size., please review it. Thank you!
=> fix(profile):  resolve multiple image/video upload and media size

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/profile.php
I already fix the issue when uploading or sharing the image/video is not appearing. It's visible now and working.
=> fix(profile and dashboard): resolve media upload post and share

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/profile.php, heybleepi/codes/script/dashboard.js
I already remove the inline script fot profile and dashboard, please review it. Thank you!
=> refactor(profile and dashboard):  remove inline script

heybleepi/codes/php/forgot_password.php, heybleepi/codes/stylesheet/forgot_password.css
Please check my code. Thank you.
=> feat: implement password reset functionality with token and email link

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/profile.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
Please review the changes I made. Thank you!
=> feat (profile and dashboard): add search and toggle option for comment

heybleepi/codes/php/forgot_password.php
Please check if there are any issues in my code.
=> feat: Update changes in forgot password

heybleepi/codes/php/create_album.php, heybleepi/codes/php/dashboard.php, heybleepi/codes/php/profile.php, heybleepi/codes/php/sidebar.php, heybleepi/codes/stylesheet/dashboard.css
Please review changes for the UI and improvements. Thank you!
=> changes (profile and dashboard): add changes to UI

heybleepi/codes/php/reset_password.php
Please check my code where I updated the changes.
=> fix: update changes in reset password

heybleepi/codes/stylesheet/forgot_password.css
Please check my code and I update the styles for forgot and reset password.
=> fix: adjust styling in the forgot password feature.

heybleepi/codes/script/forgot_password.js
=> feat: add forgot-password.js

heybleepi/codes/php/create_album.php
Please review the changes for create album  feature. Thank you!
=> change(create album): improve UI and fix multiple upload

heybleepi/codes/php/index.php
I changed the path of CSS and JS for form.
=> test(form): change path

heybleepi/codes/php/index.php
I updated the path of CSS and JS for form.
=> test(path): change path of css and js for form.

heybleepi/codes/php/dashboard.php
I updated the path of CSS, JS, and assets from dashboard.
=> path(dashboard): update paths of dashboard.

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/messages.php, heybleepi/codes/php/profile.php
I updated the paths of messages and profile.
=> update paths of messages and profile.

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/messages.php, heybleepi/codes/php/profile.php, heybleepi/codes/php/settings.php
I updated the path of settings.
=> Update settings path.

heybleepi/codes/php/oauth_authorize.php
It checks for an existing token so that it wont increment tokens for the next Oauth login
=> fix(oauth authorize): fix the 'approve' condition

heybleepi/codes/php/update_settings.php
I added a feature for username validation in settings.
=> feat(settings): add username validation.

heybleepi/codes/php/index.php
Please check if I already attach the href for forgot password.
=> fix(forgot_password): add link to forgot_password page

heybleepi/codes/stylesheet/dashboard.css
=> style(profile): fix spacing

heybleepi/codes/php/index.php, heybleepi/codes/stylesheet/form_style.css
I refactor the form. Please check if there are any issues, thank you.
=> Refactor-delima

heybleepi/codes/php/index.php
I changed the class name of some input fields.
=> changes(form): update class names.

heybleepi/codes/php/configuration.php
Changed the timezone into Philippines (Asia/Manila) in the configuration file so that it will give a accurate time for token creation and expiration.
=> feat(configuration): change timezone to Philippines

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/profile.php, heybleepi/codes/stylesheet/dashboard.css
Please review the change for location css style, thank you!
=> sytle(location): fix white background and close button alignment

heybleepi/codes/stylesheet/dashboard.css
Please review the changes for location feature
=> styles(location): fix overlapping of buttons and styles

heybleepi/codes/php/dashboard.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
Please review the changes for the location feature. The pinned map location is visible now when posting it. However, I am still fixing the preview when creating a post because the pinned map is not visible unliked in media preview. Thank you!
=> feature(location): add pinned location to post

heybleepi/codes/php/dashboard.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
I already resolve the problem with the visibility of map location preview on dashboard.
=> fix(location):  resolve location map preview on dashboard

heybleepi/codes/php/configuration.php
I restore the configuration.php
=> changes(config): restore config.

heybleepi/codes/stylesheet/messages.css
Please check my code I update the background. Thank you!
=> style(messages): update background and border styles for comment box

heybleepi/codes/stylesheet/form_style.css
Please check the code if there any issues.
=> fix: update login/register styles

heybleepi/codes/php/profile.php, heybleepi/codes/stylesheet/dashboard.css
Please review the changes for profile UI
=> styles(profile): add changes to profile UI

heybleepi/codes/stylesheet/forgot_password.css
Please review I apply changes in styles for reset password.
=> styles(reset_password): add padding and font size

heybleepi/codes/stylesheet/dashboard.css
Please review the changes for profile tabs
=> styles(profile-tabs): fix margin

heybleepi/codes/php/messages.php, heybleepi/codes/script/messages.js, heybleepi/codes/stylesheet/messages.css
Please review I apply changes in styles.
=> styles(messages): change button styles and modal appearance

README.md
Please check I made a changes in our URL.
=> update changes to URL

heybleepi/codes/php/notification.php, heybleepi/codes/php/sidebar.php, heybleepi/codes/stylesheet/dashboard.css
Please review the notification page and I also add changes to the sidebar.php
=> feat(notification): add page for notification

heybleepi/codes/php/settings.php, heybleepi/codes/php/update_password.php, heybleepi/codes/php/update_settings.php, heybleepi/codes/script/settings.js, heybleepi/codes/stylesheet/settings.css
I adjusted the Ui for settings.
=> changes(settings): adjust the UI based on the dashboard.

heybleepi/codes/php/oauth_authorize.php, heybleepi/codes/php/reset_password.php
Please review the code I made changes for the pathing.
=> fix(oauth & reset): update redirect paths

heybleepi/codes/php/settings.php
I added extra scope for "change password" button and birthdate field. Please check if there are any issues, thank you.
=> changes(settings): add extra scopes

heybleepi/codes/php/create-post.php, heybleepi/codes/php/receive-post.php, heybleepi/codes/php/settings.php, heybleepi/codes/stylesheet/dashboard.css
Please check if there are any issues. thank you
=> changes(external share post): add changes to the share post where the media is downloaded to the uploads directory.

heybleepi/codes/php/like_toggle.php, heybleepi/codes/php/notification.php
The like and comment for notification is already visible.
=> fix(notification): inserting like and comment to notification

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/notification.php, heybleepi/codes/php/profile.php, heybleepi/codes/php/share_post.php, heybleepi/codes/php/share_toggle.php
The share post visibility for location is now okay and I already fix the timestamp issue from having negative seconds
=> fix (profile and dashboard): fix share post visibility and timestamp

heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
Please check if the modal for profile.php is already fixed
=> fix(profile): fix modal for create post

heybleepi/codes/php/dashboard.php, heybleepi/codes/php/messages.php, heybleepi/codes/php/notification.php, heybleepi/codes/php/profile.php, heybleepi/codes/php/profile_edit.php, heybleepi/codes/php/search.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
Please review the delete confirmation modal for profile and dashboard
=> feat: add delete confirmation modal

heybleepi/codes/script/dashboard.js
please review the correct path for delete modal
=> fix: add changes to path for delete confirmation modal

heybleepi/codes/php/messages.php, heybleepi/codes/script/messages.js, heybleepi/codes/stylesheet/messages.css
I update changes in styles and js. Kindly check the code. Thank you
=> fix(messages): update changes in styles and edit button in js

heybleepi/codes/stylesheet/dashboard.css
I adjust the styles in comment section
=> styles(dashboard): adjust styles in toggle options

heybleepi/codes/php/oauth_authorize.php, heybleepi/codes/php/oauth_callback.php, heybleepi/codes/stylesheet/forgot_password.css, heybleepi/codes/stylesheet/oauth_authorize.css
Please check if the new theme for oauth authorization to devhive and hershive is already good to you. thank you.
=> styles(oauth_authorization): apply new UI

heybleepi/codes/php/add_comment_dashboard.php, heybleepi/codes/php/add_comment_profile.php, heybleepi/codes/php/dashboard.php, heybleepi/codes/php/delete_comment_dashboard.php, heybleepi/codes/php/delete_comment_profile.php, heybleepi/codes/php/edit_comment_dashboard.php, heybleepi/codes/php/edit_comment_profile.php, heybleepi/codes/php/profile.php, heybleepi/codes/php/search.php, heybleepi/codes/script/dashboard.js, heybleepi/codes/stylesheet/dashboard.css
Please check the code I add an AJAX for comment.
=> fix(dashboard & profile): add an AJAX for comment in dashboard and profile

heybleepi/codes/php/reset_password.php
I add an icon for input password.
=> fix(reset): add an icon for input password

heybleepi/codes/php/oauth_authorize.php, heybleepi/codes/stylesheet/oauth_authorize.css
I update the changes font in oauth.
=> fix(oauth): change the font in oauth
